repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python_venv
        language_version: python3.11
        files: (src|tests)/.*\.py$
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python_venv
        files: (src|tests)/.*\.py$
  - repo: local
    hooks:
      - id: yamllint
        name: yamllint
        entry: yamllint
        language: python_venv
        types: [yaml]
        files: \.yml$
